### ISSUE TITLE
No effect on wifi

### ISSUE THREAD

**Issue by 61Halim** [jakeajames/RealCC#1] opened 2018-01-22 21:38 UTC
I install it, and no effect on wifi icon on cc. It is normal, how it works?

**Comment by jakeajames** [comment] 2018-01-24 14:27
It should disable wifi when you tap on it

**Comment by 61Halim** [comment] 2018-01-25 14:46
No wifi doesn´t work, if I click on wifi toogle  it disconnected from my wifi but it doesn´t disabled.
Bluetooth works, if I click the toogle it disabled bluetooth

**Comment by Packetfahrer** [comment] 2018-01-25 14:58
@61Halim can you Tell me the Title in your Setting´s for Wifi or your Language ?

**Comment by 61Halim** [comment] 2018-01-25 14:59
The title is WLAN my language is German

**Comment by Packetfahrer** [comment] 2018-01-25 15:03
Ok then wait a little bit, this is Fixed in my Pull request. 
Auf deutsch warte bis er meinen Fix implementiert hat. :)

**Comment by 61Halim** [comment] 2018-01-25 15:11
Ah ok thanks, then I will wait for the update

**Comment by Namouk** [comment] 2018-01-26 22:17
@jakeajames  @Packetfahrer 

Your last update (0.0.1-14) still doesn't work for phones displaying WLAN instead of wifi in the settings.

To fix it you need to change 

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WIFI_NAME"`

to

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WLAN_NAME"`

I can confirm it works just as intended.

Thanks for this great tweak!

**Comment by 61Halim** [comment] 2018-01-26 22:51
@Namouk how and which file to change?

**Comment by Namouk** [comment] 2018-01-26 23:03
@61Halim 

If you don't know, you better wait a little until they update it.

**Comment by 61Halim** [comment] 2018-01-26 23:13
Edit: It works!

**Closed as completed** 2018-01-26 23:13 UTC
